mzcnfrnce/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings

from dbemail.views import send_mail


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
    url(r'^admin/send-email/$', send_mail, name='send_mail'),
    url("^talks/", include('talks.urls')),
    url("^robots\.txt$", direct_to_template, {"template": "robots.txt"}, name="robot-txt"),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += patterns('',
        url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),
    )

urlpatterns += patterns('',
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

talks/urls.py
from django.conf.urls import patterns, url

from talks.views import (
    TalkCreate, TalkDelete, TalkUpdate, TalkView, UsersTalks, FullPaperSubmit, get_profile, PublicUserTalks)

urlpatterns = patterns(
    '',
    url(r'^$', UsersTalks.as_view(), name='users_talks'),
    url(r'^page/(?P<page>\d+)$', UsersTalks.as_view(),
        name='users_talks_page'),
    url(r'^new/$', TalkCreate.as_view(), name='talk_submit'),
    url(r'^(?P<pk>\d+)/$', TalkView.as_view(), name='talk_detail'),
    url(r'^(?P<pk>\d+)/edit/$', TalkUpdate.as_view(),
        name='talk_edit'),
    url(r'^(?P<pk>\d+)/delete/$', TalkDelete.as_view(),
        name='talk_delete'),
    url(r'^(?P<pk>\d+)/fullpaper/$', FullPaperSubmit.as_view(),
        name='talk_submit_fullpaper'),
    url(r'^get-profile/(?P<profile_id>\d+)/$', get_profile,
        name='get_profile'),
    url(r'^accepted/(?P<username>[\w.@+-]+)/$', PublicUserTalks.as_view(), name='public_usertalks'),
)

talks/models.py
import os
#import magic
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.encoding import python_2_unicode_compatible

from mezzanine.core.models import SiteRelated, Ownable, Orderable
from mezzanine.conf import settings as mezzanine_settings

from utils.files import get_abstracts_path
from utils.files import get_fullpapers_path

from dbemail.models import EmailTemplate
from profiles.models import Profile

# constants to make things clearer elsewhere
ACCEPTED = 'A'
PENDING = 'P'
REJECTED = 'R'
EMPTY = 'E'

'''
def validate_file_extension(value):
    content_types = mezzanine_settings.TALKS_FILE_CONTENT_TYPES
    content_types = content_types.split(',')
    if content_types:
        content_type = magic.from_buffer(value.file.read(), mime=True)
        if content_type not in content_types:
            raise ValidationError(mezzanine_settings.TALKS_FILE_CONTENT_TYPE_ERROR_MESSAGE)
        
def validate_pdf_file(value):
    content_type = magic.from_buffer(value.file.read(), mime=True)
    if content_type != 'application/pdf':
        raise ValidationError(u'Unsupported file type.')
        
def validate_zip_file(value):
    ZIP_CONTENT_TYPES=['application/x-compressed', 'application/x-zip-compressed',
                       'application/zip', 'multipart/x-zip', 'application/x-rar']
    content_type = magic.from_buffer(value.file.read(), mime=True)
    if content_type not in ZIP_CONTENT_TYPES:
        raise ValidationError(u'Only .zip and .rar files are allowed.')
'''

def validate_file_extension(value):
    extensions = mezzanine_settings.TALKS_FILE_EXTENSIONS
    extensions = extensions.replace(' ', '')
    extensions = extensions.split(',')
    if extensions:
        file_name, ext = os.path.splitext(value.file.name)
        if ext not in extensions:
            raise ValidationError(mezzanine_settings.TALKS_FILE_CONTENT_TYPE_ERROR_MESSAGE)
        
def validate_pdf_file(value):
    file_name, ext = os.path.splitext(value.file.name)
    if ext not in ['.pdf', ]:
        raise ValidationError(u'Unsupported file type.')
        
def validate_zip_file(value):
    file_name, ext = os.path.splitext(value.file.name)
    if ext not in ['.zip', '.rar']:
        raise ValidationError(u'Only .zip and .rar files are allowed.')

@python_2_unicode_compatible
class TalkType(SiteRelated):
    """A type of talk."""
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1024)

    def __str__(self):
        return u'%s' % (self.name,)
    
@python_2_unicode_compatible
class TalkSubject(SiteRelated):
    """A type of talk."""
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1024)
    order = models.IntegerField(default=0)
    
    class Meta:
        ordering = ('order', 'name')
        
    def __str__(self):
        return u'%s' % (self.name,)

@python_2_unicode_compatible
class Talk(SiteRelated, Ownable):
    class Meta:
        permissions = (
            ("view_all_talks", "Can see all talks"),
        )

    TALK_STATUS = (
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Not Accepted'),
        (PENDING, 'Under Consideration'),
        (EMPTY, 'Not Submitted')
    )
    
    talk_type = models.ForeignKey(TalkType, null=True, verbose_name="Type")
    talk_subject = models.ForeignKey(TalkSubject, null=True, verbose_name="Subject")

    title = models.CharField(max_length=1024)

    abstract = models.FileField(_('File'), max_length=255, upload_to=get_abstracts_path, validators=[validate_file_extension])
    abstract_pdf = models.FileField(_('File (PDF)'), max_length=255, blank=True, null=True, upload_to=get_abstracts_path,validators=[validate_pdf_file])
    notes = models.TextField(
        null=True, blank=True,
        help_text=_("Any notes for the conference organisers?"))

    status = models.CharField(max_length=1, choices=TALK_STATUS,
                              default=PENDING)
    
    fullpaper = models.FileField(_('Full Paper'), null=True, blank=True, max_length=255, upload_to=get_fullpapers_path, validators=[validate_pdf_file],
                                help_text='Only .pdf files')
    fullpaper_pdf = models.FileField(_('Full Paper (PDF)'), max_length=255, blank=True, null=True, upload_to=get_fullpapers_path,validators=[validate_pdf_file])
    fullpaper_status = models.CharField(max_length=1, choices=TALK_STATUS,
                              default=EMPTY)

    def __str__(self):
        return u'%s: %s' % (self.user, self.title)

    def get_absolute_url(self):
        return reverse('talk_detail', args=(self.pk,))

    def get_author_contact(self):
        email = self.corresponding_author.email
        profile = self.corresponding_author
        if profile.phone:
            contact = profile.phone
        else:
            # Should we wrap this in a span for styling?
            contact = 'NO CONTACT INFO'
        return '%s - %s' % (email, contact)
    get_author_contact.short_description = 'Contact Details'

    def get_author_name(self):
        return '%s (%s)' % (self.corresponding_author,
                            self.corresponding_author.get_full_name())

    get_author_name.admin_order_field = 'corresponding_author'
    get_author_name.short_description = 'Corresponding Author'

    def get_author_display_name(self):
        full_name = self.user.get_full_name()
        if full_name:
            return full_name
        return self.user.username
    
    def get_authors_display(self):
        return ', '.join([author.name for author in self.authors.all()])
        
    def get_in_schedule(self):
        if self.scheduleitem_set.all():
            return True
        return False

    get_in_schedule.short_description = 'Added to schedule'
    get_in_schedule.boolean = True

    def has_url(self):
        """Test if the talk has urls associated with it"""
        if self.talkurl_set.all():
            return True
        return False

    has_url.boolean = True

    # Helpful properties for the templates
    accepted = property(fget=lambda x: x.status == ACCEPTED)
    pending = property(fget=lambda x: x.status == PENDING)
    rejected = property(fget=lambda x: x.status == REJECTED)
    
    # Helpful properties for the templates
    fullpaper_accepted = property(fget=lambda x: x.fullpaper_status == ACCEPTED)
    fullpaper_pending = property(fget=lambda x: x.fullpaper_status == PENDING)
    fullpaper_rejected = property(fget=lambda x: x.fullpaper_status == REJECTED)
    fullpaper_empty = property(fget=lambda x: x.fullpaper_status == EMPTY)

    def can_view(self, user):
        if user.has_perm('talks.view_all_talks'):
            return True
        if self.user.pk == user.pk:
            return True
        if self.accepted:
            return True
        return False

    @classmethod
    def can_view_all(cls, user):
        return user.has_perm('talks.view_all_talks')

    def can_edit(self, user):
        #if user.has_perm('talks.change_talk'):
        #    return True
        if self.pending:
            if self.user.pk == user.pk:
                return True
        return False
    
    def can_edit_fullpaper(self, user):
        can_submit_fullpaper = getattr(mezzanine_settings, 'TALKS_FULLPAPER_SUBMIT_OPEN', False)
        print can_submit_fullpaper
        if not can_submit_fullpaper:
            return False
        if user.has_perm('talks.change_talk'):
            return True
        if self.fullpaper_empty or self.fullpaper_pending:
            if self.user.pk == user.pk:
                return True
        return False
    
    def abstract_status_class(self):
        if self.pending:
            return 'label-info'
        elif self.accepted:
            return 'label-success'
        elif self.rejected:
            return 'label-danger'
        
    def fullpaper_status_class(self):
        if self.fullpaper_pending:
            return 'label-info'
        elif self.fullpaper_accepted:
            return 'label-success'
        elif self.fullpaper_rejected:
            return 'label-danger'
        elif self.fullpaper_empty:
            return 'label-warning'
        
    def abstract_accept_or_reject(self, status):
        if status == 'accept':
            self.status = ACCEPTED
        elif status == 'reject':
            self.status = REJECTED
            
        self.save()
        
        if mezzanine_settings.TALKS_SEND_ACCEPT_REJECT_MAIL:
            template_slug = status
            to_address = self.user.email
            context = {'user': self.user, 'talk': self,}
            return EmailTemplate.send_template(template_slug, to_address, context,)
        return True
    
    def fullpaper_accept_or_reject(self, status):
        if status == 'accept':
            self.fullpaper_status = ACCEPTED
        elif status == 'reject':
            self.fullpaper_status = REJECTED
            
        self.save()
        
        if mezzanine_settings.TALKS_SEND_ACCEPT_REJECT_MAIL:
            template_slug = 'fullpaper-%s' % status
            to_address = self.user.email
            context = {'user': self.user, 'talk': self,}
            return EmailTemplate.send_template(template_slug, to_address, context,)
        return True
'''
@python_2_unicode_compatible
class fullpaper(SiteRelated, Ownable):
    TALK_STATUS = (
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Not Accepted'),
        (PENDING, 'Under Consideration'),
    )
    
    talk = models.ForeignKey(Talk)

    fullpaper = models.FileField(_('File'), max_length=255, upload_to=get_abstracts_path, validators=[validate_zip_file],
                                help_text='Only .zip or .rar files')

talks/forms.py
from django import forms
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth import get_user_model
from django.forms.models import inlineformset_factory

from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, HTML
from crispy_forms.layout import Layout, Field, Div

from talks.models import Talk, Author

UserModel = get_user_model()

class AuthorForm(forms.ModelForm):
    name = forms.CharField(label=_('name'), max_length=100, required=False)
    email = forms.EmailField(label=_('email'), required=False)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        profile = cleaned_data.get('profile', None)
        name = cleaned_data.get('name', None)
        email = cleaned_data.get('email', None)
        if not profile and (not name or not email):
            raise forms.ValidationError(_('Provide either user or [name and email]'))
        return cleaned_data
        
    class Meta:
        model = Author
        fields = ('profile', 'name', 'email', 'is_presenter',)


class TalkForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels = True
    helper.form_tag = False
    helper.layout = Layout(
        Div(
            Div('talk_type', css_class='col-md-6'),
            Div('talk_subject', css_class='col-md-6'),  
            css_class='row'
        ),
        Div(
            Div('title', css_class='col-md-12'),
            css_class='row'
        ),
        
        Div(
            Div('abstract', css_class='col-md-12'),
            css_class='row'
        ),
                           
        Div(
            Div('fullpaper', css_class='col-md-12'),
            css_class='row'
        ),
    )
    class Meta:
        model = Talk
        fields = ('title', 'talk_type', 'talk_subject', 'abstract')
        
class FullPaperForm(forms.ModelForm):
    class Meta:
        model = Talk
        fields = ('fullpaper', )
        
AuthorFormSet = inlineformset_factory(Talk, Author,
                                            form=AuthorForm, extra=3, max_num=7)

class AuthorFormSetHelper(FormHelper):
    template = 'bootstrap/table_inline_formset.html'
    def __init__(self, *args, **kwargs):
        super(AuthorFormSetHelper, self).__init__(*args, **kwargs)
        self.add_input(Submit("submit", "Save"))

templates/talks/aippaper_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}
{% block title %}
{% trans "AIP Paper Submission" %}
{% endblock %}
{% block main %}
<section class="wafer wafer-talk-edit">
{% if not can_edit %}
{% blocktrans %}
<em>AIPPaper submission is closed</em>
{% endblocktrans %}
{% else %}
<form action="." method="post" class="form" enctype="multipart/form-data">
	{{ form.media }}
	{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" class="btn btn-danger" value="{% trans 'Submit' %}">
</form>
{% endif %}
</section>
{% endblock %}

templates/talks/fullpaper_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}
{% block title %}
{% trans "Full Paper Submission" %}
{% endblock %}
{% block main %}
<section class="wafer wafer-talk-edit">
{% if not can_edit %}
{% blocktrans %}
<em>Full-Paper submission is closed</em>
{% endblocktrans %}
{% else %}
<form action="." method="post" class="form" enctype="multipart/form-data">
	{{ form.media }}
	{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" class="btn btn-danger" value="{% trans 'Submit' %}">
</form>
{% endif %}
</section>
{% endblock %}

templates/talks/public_talks.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Abstracts' %}: {{ profile.name }}{% endblock %}
{% block main %}
<ul>
{% for talk in talk_list %}
<li>
	{% if talk.abstract_pdf %}
	<a href="{{ talk.abstract_pdf.url }}" target="_blank">{{ talk.title }}</a>
	{% else %}
	{{ talk.title }}
	{% endif %}
</li>
{% endfor %}
</ul>
{% endblock %}

templates/talks/talk.html
{% extends "base.html" %}
{% load i18n %}
{% block title_base %}{% endblock %}
{% block main %}
<section class="wafer wafer-talk">
<h1>
    {{ object.title }}
</h1>
<div>
    <p>
    {% blocktrans count counter=object.authors.count %}
    Speaker:
    {% plural %}
    Speakers:
    {% endblocktrans %}
    {{ object.get_authors_display }}
    </p>
    <p>
    Type:
    {{ object.talk_type.name|default:'Talk' }}
    </p>
</div>
<div>
    <p>
    {% trans 'Status:' %}
    {% if object.pending %}
    <span class="label label-warning">{% trans 'Under consideration' %}</span>
    {% elif object.accepted %}
    <span class="label label-success">{% trans 'Accepted' %}</span>
    {% else %}
    <span class="label label-danger">{% trans 'Not accepted' %}</span>
    {% endif %}
    </p>
</div>
<h3>Files</h3>
<div class="well" id="urls">
   {% if object.abstract_pdf %}
   <p><a href="{{ object.abstract_pdf.url }}" target="_blank">{% trans 'Short Abstract' %}</a></p>
   {% endif %}
   {% if object.fullpaper_pdf %}
   <p><a href="{{ object.fullpaper_pdf.url }}" target="_blank">{% trans 'Full Paper' %}</a></p>
   {% endif %}
</div>
</section>
{% endblock %}

templates/talks/talk_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Confirm Talk Deletion" %}{% endblock %}
{% block main %}
<section class="wafer wafer-talk-delete">
<div class="alert alert-danger">
    {% blocktrans with talk_title=object.title talk_url=object.get_absolute_url %}
    You are about to delete the talk <a href="{{ talk_url }}">"{{ talk_title }}"</a>.<br>
    This cannot be undone.
    {% endblocktrans %}
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="{% trans 'Confirm Deletion' %}">
</form>
</section>
{% endblock %}

templates/talks/talk_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static "chosen/chosen.min.css" %}">
{% endblock %}
{% block extra_js %}
<script src="{% static "chosen/chosen.jquery.min.js" %}"></script>
<script type="text/javascript">
jQuery(function($) {
	$('#authors select').chosen().on('change', function (e) {
	    id = $(this).val();
	    var name_field = $(this).closest('tr').find('.textinput');
	    var email_field = $(this).closest('tr').find('.emailinput');
	    if (id){
		    $.ajax({
	            type: "GET",
	            url: "/talks/get-profile/" + id,
	            dataType: "json",
	            success: function(data) {
	            	name_field.val(data.name);
	            	email_field.val(data.email);
	            }
	        });
	    }
	});
});
</script>
{% endblock %}
{% block title %}
{% if can_edit %}
{% trans "Edit Abstract" %}
{% else %}
{% trans "Edit Abstract" %}
{% endif %}
{% endblock %}
{% block main %}
<section class="wafer wafer-talk-edit">
{% if not can_edit and not can_submit %}
{% blocktrans %}
<em>Talk submission is closed or you haven't edit permission this talk.</em>
{% endblocktrans %}
{% else %}
<form action="." method="post" class="form" enctype="multipart/form-data">{% csrf_token %}
	{{ form.media }}
	{% crispy form %}
	<h3 style='border-bottom:1px dotted #0d0d0d;'>{% trans 'Authors' %}</h3>
	<div id="authors">
	{% crispy authors helper %}
	</div>
</form>
{% endif %}
</section>
{% endblock %}

templates/talks/talks.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Abstracts' %}{% endblock %}
{% block main %}
<div style="margin-bottom:10px;">
	<span class="label label-info">{% trans 'Under Consideration' %}</span>
	<span class="label label-success">{% trans 'Accepted' %}</span>
	<span class="label label-danger">{% trans 'Rejected' %}</span>
</div>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>{% trans 'Title' %}</th>
			<th>{% trans 'Authors' %}</th>
			<th>{% trans 'Status' %}</th>
			<th>{% trans 'Actions' %}</th>
		</tr>
	</thead>
	<tbody>
    {% for talk in talk_list %}
    <tr class="{{ talk.css_class }}">
    	<td>{{ talk.title }}</td>
    	<td>{{ talk.get_authors_display }}</td>
    	<td>
    		{% trans 'Short Abstract' %}: <span class="label {{ talk.abstract_status_class }}">{{ talk.get_status_display }}</span>
    		<br />{% trans 'Full Paper' %}: <span class="label {{ talk.fullpaper_status_class }}">{{ talk.get_fullpaper_status_display }}</span>
    	</td>
    	<td>
    		<div class="btn-group">
			  <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#">
			    {% trans 'Actions' %}
			    <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu">
			    {% if talk.pending %}
		    		<li><a href="{% url 'talk_edit' talk.pk %}">{% trans 'Edit' %}</a></li>
		    		<li><a href="{% url 'talk_delete' talk.pk %}">{% trans 'Delete' %}</a></li>
		    	{% endif %}
		    	{% if can_submit_fullpaper %}
		    	{% if talk.fullpaper_empty or talk.fullpaper_pending %}
		    		<li><a href="{% url 'talk_submit_fullpaper' talk.pk %}">{% trans 'Submit Full Paper' %}</a></li>
		    	{% endif %}
		    	{% endif %}
			  </ul>
			</div>
    	</td>
    </tr>
    {% empty %}
    <p>No abstracts accepted yet.</p>
    {% endfor %}
    </tbody>
</table>
{% if is_paginated %}
<section class="wafer wafer-pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li><a href="{% url 'wafer_users_talks_page' page=page_obj.previous_page_number %}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
        <li><a href="{% url 'wafer_users_talks_page' page=page %}">{{ page }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a href="{% url 'wafer_users_talks_page' page=page_obj.next_page_number %}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
        {% endif %}
    </ul>
</section>
{% endif %}
{% endblock %}